### ISSUE TITLE
Feature: Adding repos to groups

### ISSUE THREAD

**Issue by mkohn** [DrFaust92/terraform-provider-bitbucket#130] opened 2022-12-30 16:01 UTC
I would like the ability to add repository to groups.

**Comment by DrFaust92** [comment] 2023-01-01 20:50
unless @mkohn can elaborate i think this is duplicate of https://github.com/DrFaust92/terraform-provider-bitbucket/issues/109

**Closed** 2023-01-01 22:13 UTC

**Comment by mkohn** [comment] 2023-01-01 22:25
Sorry you are correct I missed that when I looked through the issues. We should close this as a duplicate.

**Comment by DrFaust92** [comment] 2023-01-02 08:05
[mkohn](https://github.com/mkohn) added in 2.28.0 version
